/**
 * Validate every entity individually.
 *
 * `omcValidate` defaults to atomic, which collapses the whole set to a single boolean. That
 * is useless for a report — run it non-atomically so a failure names the entity and the
 * offending property.
 *
 * @memberof namespace:DataPipeline
 * @function validateEntities
 * @param {Array<OmcEntity>} entities - Entities to check
 * @returns {DataPipeline.ValidationResult} Result, with per-entity failures
 */
export function validateEntities(entities: Array<OmcEntity>): DataPipeline.ValidationResult;
/**
 * Check that every edge target resolves to an entity in the bundle.
 *
 * An edge is just an identifier, so a mis-seeded reference produces a syntactically valid
 * entity pointing at nothing. Only references to types the bundle actually contains are
 * checked — a deliberate reference out to an entity generated by a later pass is expected
 * and is reported separately as `external`.
 *
 * @memberof namespace:DataPipeline
 * @function checkEdgeTargets
 * @param {Object.<string, Array<OmcEntity>>} entitiesByType - Entity type to entities
 * @returns {DataPipeline.EdgeCheck} Unresolved references
 */
export function checkEdgeTargets(entitiesByType: {
    [x: string]: OmcEntity[];
}): DataPipeline.EdgeCheck;
/**
 * Validate a bundle and check its edges, without writing anything.
 *
 * The checks a bundle must pass before it is fit to leave the process, whether that is to a
 * directory or to a caller over HTTP. Nothing here touches the filesystem, so a service can
 * seal a bundle it never intends to store.
 *
 * @memberof namespace:DataPipeline
 * @function sealBundle
 * @param {Object} params
 * @param {Object.<string, Array<OmcEntity>>} params.entitiesByType - Entity type to entities
 * @returns {{validation: DataPipeline.ValidationResult, edgeCheck: DataPipeline.EdgeCheck, counts: Object.<string, number>}}
 *   Validation, edge check and per-type entity counts
 */
export function sealBundle({ entitiesByType }: {
    entitiesByType: {
        [x: string]: Array<OmcEntity>;
    };
}): {
    validation: DataPipeline.ValidationResult;
    edgeCheck: DataPipeline.EdgeCheck;
    counts: {
        [x: string]: number;
    };
};
/**
 * The message describing a failed validation, naming the first offender.
 *
 * @param {DataPipeline.ValidationResult} validation - The result to describe
 * @param {number} total - How many entities were checked
 * @returns {string} The message
 */
export function validationFailureMessage(validation: DataPipeline.ValidationResult, total: number): string;
/**
 * Validate and write an OMC bundle, one file per entity type.
 *
 * Nothing is written unless every entity validates: a half-written bundle that loads
 * without complaint is worse than no bundle.
 *
 * @memberof namespace:DataPipeline
 * @function writeBundle
 * @param {Object} params
 * @param {Object.<string, Array<OmcEntity>>} params.entitiesByType - Entity type to entities
 * @param {string} params.outDir - Directory to write into
 * @returns {Promise<DataPipeline.BundleResult>} Paths written, validation and edge check
 * @throws {Error} When any entity fails validation
 */
export function writeBundle({ entitiesByType, outDir }: {
    entitiesByType: {
        [x: string]: Array<OmcEntity>;
    };
    outDir: string;
}): Promise<DataPipeline.BundleResult>;
//# sourceMappingURL=bundle.d.ts.map